version: "2.1"

services:
  xqueue:
    container_name: "xqueue"
    #   build: ./
    image: chargosudar/xqueue-custom:latest
    volumes:
      - .:/edx/app/xqueue
    networks:
      default:
        aliases:
          - edx.devstack.xqueue
    ports:
      - 18040:18040
